import { ARCHETYPES, CHARACTERS, CARDS } from './data.js';
import { ACHIEVEMENTS, buildExclusions } from './campaign.js';
import { BATTLE_ASSETS } from './battle-art.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(id,label,description='',extra='')=>`<button data-menu="${id}" ${extra}><span>${label}</span>${description?`<small>${description}</small>`:''}</button>`;
const back=()=>button('back','← 返回','','class="menu-back"');
const date=value=>value?new Date(value).toLocaleString('zh-TW',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'';
export function menuView({screen,campaign,profile,builds,notice,feedback,seed}) {
  const message=`<p class="menu-feedback" role="status">${esc(notice||feedback)}</p>`;
  if(screen==='title') return `<section class="title-scene" aria-label="主選單"><div class="title-content"><p class="menu-kicker">RIFTBOUND · 跨宇宙卡牌冒險</p><h1>裂界牌局</h1><p class="title-tagline">一副牌，穿越無數世界。</p><nav class="title-options" aria-label="遊戲選單">${button('play','進入遊戲','CONTINUE THE JOURNEY','class="title-primary"')}${button('achievements','查看成就',`${campaign.achievements.length} / ${ACHIEVEMENTS.length} 已解鎖`)}${button('collection','卡牌收藏',`${Object.values(profile.collection).filter(n=>n>0).length} 種已收藏`)}<button data-tutorial-open><span>玩法教學</span><small>共鳴 · 蓄氣 · 跨界接力</small></button></nav>${message}</div><footer class="title-footer"><span>七層裂界 · 三名旅人 · 無限構築</span><span>本機自動存檔 · 原型 v0.3</span></footer></section>`;
  const heading={play:['選擇冒險','你的下一段旅程'],setup:['新的遊戲','01 / 冒險設定'],achievements:['旅人成就','每一次冒險，都留下痕跡'],replace:['開始新的旅程？','目前進度將被替換']}[screen];
  let content='';
  if(screen==='play') {
    const run=campaign.run, character=run&&CHARACTERS.find(c=>c.id===run.characterId);
    content=`<div class="journey-options"><button class="journey-card continue-card" data-menu="continue" ${run?'':'disabled'}><span class="journey-icon">↻</span><strong>繼續上次進度</strong>${run?`<span class="save-portrait sprite-sheet" style="--sprite-image:url('${BATTLE_ASSETS.heroes[character.id]}')" aria-hidden="true"></span><span>${esc(character.name)} · 第 ${run.step+1} / 7 層 · ${esc({map:'選擇路線',battle:`戰鬥・回合 ${run.turn}`,reward:'挑選戰利品',shop:'商店',event:'事件',camp:'營火'}[run.phase])}</span><small>生命 ${run.player.hp}/${run.player.maxHp} · ${run.deck.length} 張牌<br>存檔時間 ${date(campaign.savedAt)}</small>`:'<span>尚無進行中的冒險</span><small>從新的遊戲展開第一段旅程。</small>'}</button><button class="journey-card new-card" data-menu="new"><span class="journey-icon">✦</span><strong>新的遊戲</strong><span>設定流派，再選擇旅人</span><small>決定這一局會遇見的卡牌與遺物。</small></button></div>`;
  }
  if(screen==='setup') {
    const candidates=CHARACTERS.map(c=>({c,...buildExclusions(builds,c.id)}));
    const viable=candidates.some(c=>CARDS.filter(card=>!['strike','defend'].includes(card.id)&&!c.excludedCards.includes(card.id)).length>=3);
    content=`<div class="setup-layout"><section><h2>選擇要排除的流派</h2><p class="menu-help">預設全部開放。排除後，相關卡牌與遺物不會出現在本局；混合流派只要命中任一排除項目也會移除。</p><div class="build-options">${Object.entries(ARCHETYPES).map(([id,b],i)=>`<button data-build="${id}" aria-pressed="${builds.includes(id)}" class="build-option ${builds.includes(id)?'excluded':''}"><span class="build-sigil">${['⚔','◉','✹','⬡','♧','✦'][i]}</span><span><strong>${b.name}</strong><small>${b.description}</small></span><b class="build-state">${builds.includes(id)?'已排除':'開放'}</b></button>`).join('')}</div><button data-menu="reset-builds" class="menu-secondary">恢復全部流派</button></section><aside class="setup-summary"><p class="menu-kicker">本局設定</p><h2>${builds.length?`排除 ${builds.length} 種流派`:'完整跨界體驗'}</h2><p>${builds.length?builds.map(id=>ARCHETYPES[id].name).join('、'):'所有流派皆可出現。推薦第一次遊玩使用。'}</p><div class="fixed-rule"><b>角色固定牌永遠保留</b><p>下一步選角色後，會列出保留的固定牌；其他起始牌自動補足十張，仍可手動調整。</p></div><label class="field">冒險種子<input id="seed" value="${esc(seed)}" maxlength="48" autocomplete="off"></label>${campaign.run?'<p class="menu-help">目前存檔會保留到你確認開始新冒險。</p>':''}${button('choose-character','下一步：選擇角色','02 / 決定你的職業',`class="primary" ${viable?'':'disabled'}`)}${!viable?'<p class="menu-error">排除過多，請至少保留3種非基礎卡候選。</p>':''}</aside></div>`;
  }
  if(screen==='achievements') content=`<div class="achievement-overview"><span><b>${campaign.achievements.length}</b> / ${ACHIEVEMENTS.length} 成就</span><span>完成冒險 <b>${campaign.stats.runs}</b> 次</span><span>登塔成功 <b>${campaign.stats.wins}</b> 次</span></div><div class="achievement-grid">${ACHIEVEMENTS.map(a=>`<article class="achievement ${campaign.achievements.includes(a.id)?'unlocked':'locked'}" data-achievement="${a.id}"><span class="achievement-medal">${a.icon}</span><div><small>${campaign.achievements.includes(a.id)?'已解鎖':'尚未解鎖'}</small><h2>${a.name}</h2><p>${a.text}</p></div></article>`).join('')}</div>`;
  if(screen==='replace') content=`<section class="replace-panel"><p>開始新的冒險後，將取代目前的${esc(CHARACTERS.find(c=>c.id===campaign.run?.characterId)?.name||'旅人')}第 ${(campaign.run?.step||0)+1} 層存檔。</p><p>卡牌收藏與已解鎖成就會保留。</p><div>${button('cancel-replace','返回角色選擇')}${button('confirm-replace','開始新的冒險','','class="primary"')}</div></section>`;
  return `<section class="menu-page menu-${screen}"><header class="menu-page-header">${back()}<span>裂界牌局</span></header><div class="menu-page-body"><p class="menu-kicker">${heading[1]}</p><h1>${heading[0]}</h1>${message}${content}</div></section>`;
}
